### ISSUE TITLE
Naming return parameter

### ISSUE THREAD

**Issue by mbtools** [dominikpanzer/RESULT-for-ABAP#6]
You might want to add a benefit. Something like...

- Consistently using RESULT as the name for the returning parameter of methods simplifies method definitions and significantly improves readability of your code

**Comment by dominikpanzer** [comment]
thx for the input. yes, that's one of the main advantages. Sadly ABAP doesnt know Generics like other languages, so one disadvantage of the solution is that you don't directly know what type result->get_value( ) will return.  I am still missing a good idea for that problem

**Comment by dominikpanzer** [comment]
readme updated
