### ISSUE TITLE
ABAP_BOOLEAN not available in NW 752 SP04

### ISSUE THREAD

**Issue by christianguenter2** [dominikpanzer/RESULT-for-ABAP#8]
![grafik](https://user-images.githubusercontent.com/17437789/234808833-125d6a2b-2963-44cc-90dd-7af6c290069b.png)

**Comment by dominikpanzer** [comment]
current dev environment is a abap steampunk. I'll downport it.

**Comment by dominikpanzer** [comment]
I replaced the type with ABAP_BOOL. this should be available in "older" systems. could you please have a look Christian? Thanks.

**Comment by christianguenter2** [comment]
This one is done. More to go :-)
![grafik](https://user-images.githubusercontent.com/17437789/235075349-dbd25ca3-8b24-4082-b09b-aa2656a780da.png)

**Comment by dominikpanzer** [comment]
pure pain. I hopefully fixed it. it's available in the repo now, but haven't had the chance to test it on a 7.5x system, yet.

**Comment by christianguenter2** [comment]
Thx. Still some left ;-)
![grafik](https://user-images.githubusercontent.com/17437789/235305878-7d74874c-3c18-4248-89d6-efa421ff0383.png)

**Comment by dominikpanzer** [comment]
uhm I'll check next week when I have a system available. sorry for the trouble.

**Comment by dominikpanzer** [comment]
Hi Christian, "it works on my machine" (7.50). Import is successful and the objects are active, unit tests green.  sadly the syntax to access the result from the get_result( ) method is not very fluent :-( I'm looking forward to your feedback.

note: there's still a diff for the package and the exception classes, I opened a ticket here ... ;-) https://github.com/abapGit/abapGit/issues/6248

**Comment by christianguenter2** [comment]
Hi Dominik,
Works now 👍 Thanks for your effort.
