### ISSUE TITLE
Dererefencing result value

### ISSUE THREAD

**Issue by christianguenter2** [dominikpanzer/RESULT-for-ABAP#9]
@dominikpanzer I'm a bit confused with this part of the documentation:
```ABAP
* on older systems you can't directly dereference the value
DATA(temporary_reference) = result->get_value( ).
object_instance ?= temporary_reference->*.
```
What is `object_instance` in this case? Is `result` here related to the previous examples ( its last writing position is `result = zcl_result=>ok( 100040340 ).`?
Anyways, you cannot dereference a generic data reference in older systems with this syntax either. You first have to assign it to a field-symbol. At least on 752 SP04.

Maybe a syntax addition like this would make things easier, as the caller doesn't have to dereference the reference and save a few lines of boilerplate code.
```ABAP

    METHODS get_value EXPORTING value      TYPE any
                      RETURNING VALUE(ref) TYPE REF TO data
                      RAISING   zcx_result_is_not_ok.

```

```ABAP
DATA: partner TYPE bu_partner.

zcl_result=>ok( 100040340 )->get_value( 
  IMPORTING
    value = partner ).

```
Of course that contradicts directly this design goal:
`Ideally a method should only return one value.`
Maybe with two methods like `get_value` and `get_ref`. To either access the value directly via exporting parameter or return the reference.

**Comment by dominikpanzer** [comment]
Hey Christian. 
Thanks for actually reading the docs and your valuable feedback.

I think on old systems actually just something like this works. Code is a snippet from the unit tests:
```ABAP
  METHOD ok_result_with_object_as_value.
* can save a value with a complex data type like object reference
    DATA random_object_reference TYPE REF TO zcl_result.
    DATA temporary_value TYPE REF TO data.
    FIELD-SYMBOLS <value> TYPE REF TO zcl_result.

    random_object_reference = zcl_result=>ok( ).
    DATA(result) = zcl_result=>ok( random_object_reference ).

    temporary_value = result->get_value( ).

    ASSIGN temporary_value->* TO <value>.
    cl_abap_unit_assert=>assert_equals( msg = 'Couldnt access value' exp = random_object_reference act = <value> ).
  ENDMETHOD.
 ```
I don't like that solution, because - like you said - there is a lot of boilerplate code / "code that just exists because ABAP is complicated".

`object_instance` / `random_object_instance` is any instance that you would like to transfer as a result (lo_customer, lo_idoc, etc...) So a result can be a structure, a table, an object etc...

I've been thinking about the "dereferencing"-problem a lot while downporting the code today. I came up with two more possible solutions:
1. `REF TO data` is only needed because a `RETURNING`-parameter can't be `type any`. I like `RETURNING` because of the nice syntax. But in this case it might just be easier to use `EXPORTING` instead. This would mean dereferencing internally. (I haven't tried if this would work, but you came up with a similar idea, so I'm quite confident).
1. I could open up a second branch for 7.5-systems with either the above solution or one of your ideas


What do you think?

**Comment by christianguenter2** [comment]
Hi Dominik,

regarding this syntax on old systems, I cannot spot it in the unit tests and I don't think it works
```ABAP
object_instance ?= temporary_reference->*.
```
It'll always give "A generic reference cannot be dereferenced (->) in the current statement."

Hm, I think the `RETURNING` parameter with `REF TO data` is perfectly fine for latest ABAP systems. I wouldn't change that. It allows nice functional method calls. Second branch with 7.5 syntax I wouldn't do either as this changes the API of your little library. Downport branches should imho only change implementation details if possible.

So I vote for either a `get_value` method with combined `EXPORTING` and `RETURNING` parameter or two methods one with `EXPORTING` and one with `RETURNING`. Btw. derefenrencing internally and move to `EXPORTING` params works perfectly fine.

But I'm currently just fiddling around with the tool. So this is completely up to you :-)

**Comment by dominikpanzer** [comment]
Hi Christian,
I was talking about the "ASSIGN"-solution regarding the unit tests. sorry. I'll update the docs.

I'm honestly not very keen on setting up a second branch and I really like the functional style of `RETURNING`, too . As a consumer of a `RESULT`, you usually know what type `VALUE` has, so you can decide if you have to use the `EXPORTING` or `RETURNING` value / use `get_value` or `get_ref`.... sounds like a better idea than mine. I'll give the combined method parameters a shot. 

Every feedback is welcome, no matter if you are actually using the class or just playing around :-)

**Comment by dominikpanzer** [comment]
this...
```ABAP
  METHOD get_value.
    IF is_failure( ).
      RAISE EXCEPTION TYPE zcx_result_is_not_ok.
    ENDIF.
    IF me->value IS NOT BOUND.
      value_reference = REF #( space ).
      value = space.
    ELSE.
      value_reference = me->value.
      value = me->value->*.
    ENDIF.
  ENDMETHOD.
```
works fine until  an object reference is stored in me->value . 

```ABAP
data(object) = result->get_value( ).
```
dumps with `Conversion of type "REF TO ZCL_RESULT" to type "C LENGTH 4" not supported.`
Same effect when I use a field-symbol for dereferencing. 

```ABAP
Data: object type ref to zcl_result.
result = zcl_result->get_value( ).
```
shows an error `the result type of the functional method cannot be converted into the type of RESULT`

Any ideas?

**Comment by dominikpanzer** [comment]
I updated the repo, tests are green, I haven't had the chance to test it on 7.5, yet.

**Comment by christianguenter2** [comment]
Almost :-)
![grafik](https://user-images.githubusercontent.com/17437789/236389041-f4e6f414-3a0f-4282-9638-b4bad84acb05.png)

**Comment by dominikpanzer** [comment]
fixed.

**Comment by christianguenter2** [comment]
Thx. Works now. I'll do more experiments soon ;-)
